# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

UpdateMeansForQuadraticFunction <- function(res) {
    invisible(.Call('afCEC_UpdateMeansForQuadraticFunction', PACKAGE = 'afCEC', res))
}

CalculateEllipsesOfConfidenceForQuadraticFunction <- function(res, confidence, segments) {
    .Call('afCEC_CalculateEllipsesOfConfidenceForQuadraticFunction', PACKAGE = 'afCEC', res, confidence, segments)
}

CalculateEllipsoidsOfConfidenceForQuadraticFunction <- function(res, confidence, gridRes) {
    .Call('afCEC_CalculateEllipsoidsOfConfidenceForQuadraticFunction', PACKAGE = 'afCEC', res, confidence, gridRes)
}

afCECCppRoutine <- function(points, maxClusters, initialLabels, cardMin, costThreshold, minIterations, maxIterations, numberOfStarts, method, values, interactive) {
    .Call('afCEC_afCECCppRoutine', PACKAGE = 'afCEC', points, maxClusters, initialLabels, cardMin, costThreshold, minIterations, maxIterations, numberOfStarts, method, values, interactive)
}

